<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="http://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Object Oriented Programming

## Introduction

## class是对放入物件的抽象定义，比如HumanBeing人类

## object是丢入的物件，比如某某某人，是class的一个实例instance

## attribute类似于feature特性，有两种：一种是class attribute在确立class的时候就确定下来，对所有实例都有效；另一种是instance attribute只对基于class创造出来的object/instance有效，在object被创造的时候确立。

## class：人类，class attribute：男人，女人，眼睛颜色。

## method：class可以进行的操作：如走路

## parameter: 参数，通过method输入，影响object的状态，比如，对于HumanBeing这个class里面的object人，可以做走3步的参数。

## instantiation实例化，基于某个抽象的class创造某个具体的object的过程。

### 这个例子就是定义一个关于人类的抽象集合，里面的有人的一系列特征attribute，在创造class的时候就规定下来，包括first_name, eye_color等，将人设定在原点，再定义method走路，输入parameter走几步。

In [2]:
class HumanBeing(object):  
    def __init__(self, first_name, eye_color):  
        self.first_name = first_name  
        self.eye_color = eye_color  
        self.position = 0  
    def walk_steps(self, steps):  
        self.position += steps  

class类似于def，只不过它只有存储的属性，不会执行什么命令，这个class的名称就是HumanBeing()，定义之后可以直接加入object使用。

输入的object相当于是self，

self.first_name = first_name，将输入的first_name这一var赋予给object，成为object的一个元素。

self.position = 0初始化，归0，方便后面再次使用的时候可以重新开始

__init__在每次实例化的时候自动调用，对象本身也是函数的一个参数，self是Python的约定关键词，不能随便变更，相当于是输入的object

In [15]:
Sandra = HumanBeing( 'Sandra','blue')  

instantiation实体化，赋予object名称和attribute属性first_name, eye_color，缺少一个attribute是无法进行object的定义的

In [9]:
type(Sandra)

__main__.HumanBeing

In [4]:
Sandra.first_name  

'Sandra'

In [5]:
Sandra.position  

0

In [6]:
Sandra.walk_steps(5)  

In [7]:
Sandra.position  

5

定义之后的object有3个属性attribute：first_name，position和eye_color，一个method：walk_steps().

attribute属性和method都是在class里面定义出来的，但因为Sandra是class里面的object，所以继承了class里面定义的全部属性和method。

In [10]:
V = HumanBeing('V', 'blue')

In [11]:
type(V)

__main__.HumanBeing

In [70]:
V

## class就是构成电脑的组键，它可以让一个object对象同时拥有属性和操作函数，所以说class本身是不执行的，但是却可以定义class里面的object可以执行的method。

## A Brief Look at Standard Objects基本的标准物件

### int整数

In [20]:
n = 5  

In [17]:
type(n)  

int

In [18]:
n.numerator  

5

In [ ]:
numerator都是n这个object的attribute，而n的class就是int，是系统自动生成的class。

In [19]:
n.bit_length()  

3

bit_length()是method，执行了寻找多少bit能够填满这个数的指令，带括号的都是method。

In [24]:
bin(n)

'0b101'

记录的时候用了3位数101所以bit_length是3位bit

In [25]:
n + n  

10

In [26]:
2 * n  

10

In [27]:
n.__sizeof__()  

28

method还可以是__sizeof__()和数学运算符号的形式。

### list清单

In [28]:
l = [1, 2, 3, 4]  

In [29]:
type(l)  

list

In [30]:
l[0]  

1

In [33]:
l.append(10)  

In [34]:
l + l  

[1, 2, 3, 4, 10, 10, 1, 2, 3, 4, 10, 10]

In [35]:
2 * l  

[1, 2, 3, 4, 10, 10, 1, 2, 3, 4, 10, 10]

In [36]:
sum(l)  

30

In [37]:
l.__sizeof__()  

104

### ndarray数列

In [38]:
import numpy as np  

In [39]:
a = np.arange(16).reshape((4, 4))  

instantiation实例化，将数字变成ndarray的形式，给a赋值，同时也使a变成ndarray数列的形态，创造出来一个object实例instance。

In [44]:
z = np.array([1, 9 ,10, 144444])
z

array([     1,      9,     10, 144444])

另一种instantiation实例化的方法是，通过np.array也可以将别的形式的object转换成ndarray数列形式的instance/object

In [45]:
a  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
type(a)  

numpy.ndarray

In [47]:
a.nbytes  

64

attribute属性

In [27]:
a.sum()  

120

In [28]:
a.cumsum(axis=0)  

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [29]:
a + a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [30]:
2 * a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [31]:
sum(a)  

array([24, 28, 32, 36])

In [32]:
np.sum(a)  

120

In [33]:
a.__sizeof__()  

112

method

### DataFrame

In [48]:
import pandas as pd  

In [49]:
df = pd.DataFrame(a, columns=list('abcd'))  

pd.DataFrame():instantiation实例化的过程

In [55]:
type(df)  

pandas.core.frame.DataFrame

In [56]:
df.columns  

Index(['a', 'b', 'c', 'd'], dtype='object')

attribute属性

In [60]:
df.sum()  

a    24
b    28
c    32
d    36
dtype: int64

In [61]:
df.cumsum()  

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [62]:
df + df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [63]:
2 * df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [64]:
np.sum(df)  

a    24
b    28
c    32
d    36
dtype: int64

In [65]:
df.__sizeof__()  

192

method

## Basics of Python Classes

In [66]:
class FinancialInstrument(object):  
    pass  

创造空的class，结尾要用pass

In [67]:
fi = FinancialInstrument()  

In [68]:
type(fi)  

__main__.FinancialInstrument

In [69]:
fi  

空的class也可以命名为object，object的种类：__main__.FinancialInstrument，object是无法打印出来的。

In [73]:
fi.__str__()  

'<__main__.FinancialInstrument object at 0x000001B13E42AB70>'

.__str__()特殊的method取回

In [74]:
fi.price = 100  

In [75]:
fi.price  

100

后面跟着.可以随时增加object的attribute，但这个attribute和相对应的值只适用于这个object，不适用于class。

In [76]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'  
    def __init__(self, symbol, price):  
        self.symbol = symbol  
        self.price = price  

author = 'Yves Hilpisch'在class之后，def之前，所以这个是不会随着object改变而改变的attribute。：class attribute

self.symbol = symbol：object attribute，会随着object的不同而改变，只不过attribute的title需要在class定义的时候通过def来确立。

当object需要创立时，在instantiation实例化的过程中，__init__(self, symbol, price)函数就会被唤醒一次，确定object级别的attribute按照class里面的顺序。

def __init__(self, symbol, price):

In [52]:
FinancialInstrument.author  

'Yves Hilpisch'

In [94]:
fi.author  

'Yves Hilpisch'

FinancialInstrument被赋予了新的attribute，fi也可以呼出后面定义的class级别的attribute。同名class具有继承的特性。

In [79]:
aapl = FinancialInstrument('AAPL', 100)  

实例化

In [84]:
aapl.symbol  

'AAPL'

In [85]:
aapl.author  

'Yves Hilpisch'

In [86]:
aapl.price = 105  

In [87]:
aapl.price  

105

In [88]:
class FinancialInstrument(FinancialInstrument):  
    def get_price(self):  
        return self.price #返回值相当于print  
    def set_price(self, price):  
        self.price = price  

In [89]:
fi = FinancialInstrument('AAPL', 100)  

In [90]:
fi.get_price()  

100

In [91]:
fi.set_price(105)  

In [92]:
fi.get_price()  

105

In [95]:
fi.price  

105

继承了旧的FinancialInstrument定义的属性，可以随时呼出

In [102]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol  
        self.__price = price  
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

#### private:self.__price私有化的attribute，被藏起来了，不能通过fi.__price 的方式访问到price的值。或者通过method的方法获得attribute的值。

In [107]:
fi = FinancialInstrument('AAPL', 100)

In [108]:
fi.get_price()  

100

In [109]:
# causes intentional error
fi.__price  

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [116]:
fi._FinancialInstrument__price  

100

In [117]:
fi._FinancialInstrument__price = 105  

In [118]:
fi.set_price(100)  

### 定义：self.position投资金融商品的价格变化，self.__position_size投资的数量。增加的是一个返回position_size，一个设置position_size，还有一个是算value:price * position_size.

In [186]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size  
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = float(position_size)
    def get_position_value(self):
        return self.__position_size * self.position.get_price()  

### financial_instrument代表之前设定的class：FinancialInstrument，意思就是PortfolioPosition里面的一个attribute是FinancialInstrument这个class里面的object：fi。
### 这种做法和class定义里面写的str的title没有关系(self.position = a也行)，和object设定时attribute的取值有关，说明object本身也可以是别的object的attribute。

#### 之前FinancialInstrument里面定义的method在PortfolioPosition里面也可以使用。

一个class下面除了第一个初始化method，定义了3个method

In [187]:
pp = PortfolioPosition(fi, 20)

In [188]:
pp

In [189]:
pp.get_position_size()

20

In [190]:
pp.get_position_value()  

2200

In [191]:
pp.position.get_price()  

110

In [192]:
pp.position.set_price(110)  

In [193]:
pp.update_position_size(30)

In [194]:
pp.position.get_price()  

110

### 平时在用函数的时候能够不断点下去：pp.position.get_price的原因：很多object的attribute是别的attribute，想要跨object访问前置的objects的method和attribute就需要通过这种形式。

In [195]:
pp.get_position_value() 

3300.0

## Python Data Model, 特殊的method的不同点是，它们可以用不同于xx.yy()的方式写出来。

In [196]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):  
        self.x = x  
        self.y = y  
        self.z = z  

x=0, y=0, z=0可以预设attribute的初始值

In [197]:
v = Vector(1, 2, 3)  

In [198]:
v  

In [199]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

__repr__将object的attribute可视化的方式

'Vector(%r, %r, %r)'本身是一个字符串str，%r是repr特有的，代表%后面会是字符串的形式（占位符），帮% (self.x, self.y, self.z)占位，打印出来会显示后面的值。

In [217]:
v = Vector(1, 2, 3)

In [218]:
v  

Vector(1, 2, 3)

In [219]:
print(v)  

Vector(1, 2, 3)


In [227]:
class Vector(Vector):
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 +
                self.z ** 2) ** 0.5  
    
    def __bool__(self):
        return bool(abs(self))

In [228]:
v = Vector(1, 2, -1)  

In [229]:
v.__abs__()

2.449489742783178

In [222]:
np.abs(v)

2.449489742783178

In [223]:
6**0.5

2.449489742783178

In [224]:
bool(v)

True

__abs__和__bool__分别可以计算出abs和bool的值。

In [230]:
v = Vector()  

In [231]:
v  

Vector(0, 0, 0)

因为预设的x=0, y=0, z=0，所以v = Vector()就相当于是Vector(0, 0, 0)

In [232]:
abs(v)

0.0

In [92]:
bool(v)

False

bool(v)是非0数为True，其他都是False。

In [233]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)  
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)  

### __add__可以像numpy一样，一一对应然后相加。__mul__是相乘一个实数。

In [234]:
v = Vector(1, 2, 3)

In [235]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [237]:
v.__add__(Vector(2, 3, 4))

Vector(3, 5, 7)

In [236]:
v * 2

Vector(2, 4, 6)

因为是系统自带的几个特别的method，所以可以用+和*直接表示。

In [250]:
class Vector(Vector):
    def __len__(self):
        return 4
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, 5]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [251]:
v = Vector(1, 2, 3)

In [252]:
len(v)

4

__len__的表达式是len()

In [253]:
v[0]

1

In [256]:
v[-2]

IndexError: Index out of range.

In [249]:
v[-1]

3

0和-3对应第一个数1，1和-2代表第二个数2，2和 -1代表第三个数3，i in [0, -3]代表的不是从-3到0，而是-3和0，从左往右从0开始加，从右往左从-1开始减。

__getitem__对应method的使用形式是v[-2]，和list的切片相似，但是不同，__getitem__可以随机输入对应的index，可以乱序。

 else: raise IndexError('Index out of range.')可以设置报错后的提醒文字。

In [102]:
# causes intentional error
# v[3]

In [257]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [258]:
v = Vector(1, 2, 3)

In [260]:
for i in range(2):  
    print(v[i])  

1
2


相当于是取出在v[i]对应位置之前的所有数据

In [106]:
for coordinate in v:  
    print(coordinate)  

1
2
3


for coordinate in v:   print(coordinate) 是__iter__的表达形式。简单说就是获取Vecter里面的所有attribute数据。

In [261]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z
    
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')
            
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

两种形式：可以是不断增补method和attribute，也可以是直接写完所有点class内容。

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>